/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormCheckboxGroup: typeof import('bootstrap-vue-next')['BFormCheckboxGroup']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTfoot: typeof import('bootstrap-vue-next')['BTfoot']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BThead: typeof import('bootstrap-vue-next')['BThead']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    DisplayCatalog: typeof import('./src/components/displayCatalog.vue')['default']
    DisplayProduct: typeof import('./src/components/displayProduct.vue')['default']
    IIconoirHome: typeof import('~icons/iconoir/home')['default']
    IMaterialSymbols123: typeof import('~icons/material-symbols/123')['default']
    IMdiCart: typeof import('~icons/mdi/cart')['default']
    IMdiEat: typeof import('~icons/mdi/eat')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    'IMdiLight:cart': typeof import('~icons/mdi-light/cart')['default']
    IMdiLightCart: typeof import('~icons/mdi-light/cart')['default']
    IMdiSq: typeof import('~icons/mdi/sq')['default']
    IMdiSqu: typeof import('~icons/mdi/squ')['default']
    IMdiTshirtCrew: typeof import('~icons/mdi/tshirt-crew')['default']
    'ISolar:tShirtBroken': typeof import('~icons/solar/t-shirt-broken')['default']
    ISolarTShirtBroken: typeof import('~icons/solar/t-shirt-broken')['default']
    Reviews: typeof import('./src/components/Reviews.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
